name: bestbuy
description: FPJ Startup

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_bloc: ^8.1.5
  otp_text_field: ^1.1.1
  dropdown_search: ^5.0.6
  dio: ^5.4.2+1
  path_provider: ^2.0.3
  flutter_linear_datepicker: ^2.0.3
  persian_number_utility: ^1.1.4
  bottom_navy_bar: ^6.0.0
  shamsi_date: ^1.0.2
  pull_to_refresh: ^2.0.0
  introduction_screen: ^3.1.14
  pushe_flutter: ^2.6.1
  responsive_framework: ^1.4.0

  flutter:
    sdk: flutter

#  flutter_localizations:
#    sdk: flutter
#  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_charts: ^25.1.38
  shared_preferences: ^2.0.8
  url_launcher: ^6.2.6
  dartssh2: ^2.8.2
  audioplayers: ^6.0.0



dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  card_swiper : ^3.0.1
  flutter_native_splash: ^2.4.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: iransans
       fonts:
         - asset: assets/fonts/IRANSansX-Regular.ttf
         - asset: assets/fonts/IRANSansX-Bold.ttf
           weight: 700
#     - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter_native_splash:
    color: "#ffffff"
    image: "assets/images/splash.png"
    android: true
    ios: true
    web: true
    android_gravity: center
    ios_content_mode: center
    fullscreen: true

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/logo.jpg"
  image_path_ios: "assets/images/logo.jpg"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/logo.jpg" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/logo.jpg" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/logo.jpg" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.jpg"
